[tool.poetry]
name = "timeseriesimputation"
version = "0.1.0"
description = "Time Series Imputation"
authors = ["Ming Doan <quangminh57dng@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
scikit-learn = "^1.6.0"
xgboost = "^2.1.3"
loguru = "^0.7.3"
tqdm = "^4.67.1"
pandas = "^2.2.3"
ipykernel = "^6.29.5"
numpy = "^2.2.1"
matplotlib = "^3.10.0"
torch = [
    { version = "^2.5.1+cu121", platform = "linux", source = "torch-cu121" },
    { version = "^2.5.1+cu121", platform = "win32", source = "torch-cu121" },
    { version = "^2.5.1", platform = "darwin", source = "pypi" },
]


[tool.poetry.group.dev.dependencies]
docker = "^7.1.0"
pyperclip = "^1.9.0"

[[tool.poetry.source]]
name = "torch-cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
